version: "3.9"

services:
  hello:
    image: cloud.canister.io:5000/auliahanifan/hello-world:${HELLO_TAG}
    ports:
      - "3000:3000"
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
