version: "3.9"

services:
  helloworld:
    image: auliahanifan/hello-world:${HELLO_TAG}
    ports:
      - "4000:3000"
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 5s
